dependencies:
    # - <organisation/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.3.0

compiler:
 solc:
   remappings:
     - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.3.0'

dotenv: .env
wallets:
   from_key: ${PRIVATE_KEY}

networks: 
    goerli:
      eth_usd_price_feed: '0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e'
      verify: true

    development:
      verify: false  
    
    ganache-local:
      verify: false 

